version: '3.8'

services:
  postgres:
    image: postgres:15

    environment:
      POSTGRES_DB: growsmart_ai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sujal

    ports:
      - "5432:5432"

  backend:
    build: ./backend

    ports:
      - "8000:8000"

    depends_on:
      - postgres